### ISSUE TITLE
Dynamic add/remove freezes in your demo

### ISSUE THREAD

**Issue by bluejamesbond** [STRML/react-grid-layout#111]
Steps to reproduce:
1. go to https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html
2. add 2 boxes
3. resize so the boxes move
4. add a couple more boxes
5. resize again
6. should be stuck now

**Comment by Puffton** [comment]
Which browser is this in? Can you reproduce in different browsers? I've used Chrome on OS X quite extensively with v0.8.5 (dynamic add/remove), without having issues with freezing.

**Comment by STRML** [comment]
Fixed in `0.10`.

**Comment by SumitsavarnJS** [comment]
I am still facing this issue, adding boxes randomly freezes the grid with pink color

**Comment by TeoAvignon** [comment]
Same on mobile with Firefox. If instead of dragging, I just do a quick click (touch), sometime my div is stuck my the placeholder color.
