### ISSUE TITLE
ResizeHandle doesn't disappear even if it's not resizable or static.

### ISSUE THREAD

**Issue by ktseo41** [STRML/react-grid-layout#1329]
Hi I am using react-grid-layout well. But react-grid-layout didn't work as intended.

 In version 0.17.1, the resizeHandle disappears when the GridLayout 'isResizable' property is assigned a value of false. However, it does not disappear in later versions. Same for the 'static' property of GridItem. Assigning static to true does not cause the resizeHandle to disappear.

![Screen Shot 2020-11-13 at 10 44 05 AM](https://user-images.githubusercontent.com/6429885/99018489-8a944c80-259d-11eb-8893-fb1a9dc7bc3e.png)

*  In version 1.1.1, you can remove the handle by allocating an empty array to 'resizaHandles' property, but it seems to be a temporary method.

**1. 0.17.1 isResizable property**
-  https://codesandbox.io/s/resizable-0171-4toh1

**2. 1.1.1 isResizable property & resizeHandles**
-  https://codesandbox.io/s/resizable-111-b0i51

If it is difficult to understand, sorry for the lack of English skills. Thank you.

**Comment by TikTikTik21** [comment]
Same problem, can someone help please.

**Comment by PhilSchwerttraeger** [comment]
I am experiencing the same issue. The last working version is 0.17.1.

**Comment by joshkay** [comment]
Same issue over here.

**Comment by Light0815** [comment]
Issue persists￼

**Comment by PhilSchwerttraeger** [comment]
@STRML Any chance this gets fixed in the future?

**Comment by STRML** [comment]
In the 1.x series, the `isDraggable` and `isResizable` properties were changed to avoid remounting the child component. In the past, we used to use that switch to determine whether or not to wrap in `<Resizable>`, now we always wrap and simply turn the event listeners on and off.

When `isResizable` is off, the class `.react-resizable-hide` is added. See this CSS, which you should add to your project:

https://github.com/react-grid-layout/react-grid-layout/blob/5cf8afb29dbf2ab373378e775219488d4e63454e/css/styles.css#L60-L62

**Comment by khanguslee** [comment]
Is there any chance that this issue can be reopened as the issue still persists in `v1.3.0`. This should still be a bug since a user might think that they can resize an grid item when they actually cannot.

**Comment by ZimNovich** [comment]
> Is there any chance that this issue can be reopened as the issue still persists in `v1.3.0`. This should still be a bug since a user might think that they can resize an grid item when they actually cannot.

Use this CSS:
```
.react-resizable-hide .react-resizable-handle {
    display: none !important;
}
```
