### ISSUE TITLE
Uncaught TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by birish2** [STRML/react-grid-layout#343]
From util.js, child.key throws error for undefined property. I'm getting a children array of ["0"] when I don't pass any children into the ReactGridLayout component. i.e:
```
render() {
 return(<ReactGridLayout {...this.props}></ReactGridLayout>);
}
```
using react 15.3.1 plus react-grid-layout 0.13.3

**Comment by STRML** [comment]
This is fixed in `0.13.7` due to use of `React.Children.map()`.

**Comment by dynnt27** [comment]
Not fixed on me, using react-grid-layout 0.16. Any thoughts on this? @STRML

**Comment by anagrath** [comment]
I am also experiencing this issue...

**Comment by scottc11** [comment]
Also experiencing this issue
