### ISSUE TITLE
Can't build examples

### ISSUE THREAD

**Issue by ivanoats** [STRML/react-grid-layout#39]
When I `npm run build-examples` I get these errors:

I also had to change the name of the loader to babel in the webpack configs...

```
ERROR in ./test/examples/0-showcase.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/10-dynamic-min-max-wh.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/1-basic.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/2-no-dragging.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/3-messy.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/6-dynamic-add-remove.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/5-static-elements.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/7-localstorage.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/8-localstorage-responsive.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/4-grid-property.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)

ERROR in ./test/examples/9-min-max-wh.jsx
Module build failed: ReferenceError: Unknown option: runtime
    at File.normalizeOptions (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:91:15)
    at new File (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:70:22)
    at Object.transform (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at transpile (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:54:24)
    at Object.module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-loader/index.js:43:24)
```

**Comment by STRML** [comment]
Thanks for the notice. This is fixed in master and the gh-pages branch now. Looks like I partially upgraded the config to `babel` from `6to5` but didn't finish it.

**Comment by ivanoats** [comment]
wow, that was quick, thanks!

after I `npm run build && npm run build-example && npm run dev`
I'm still seeing one error:

```
ERROR in ./test/dev-hook.jsx
Module build failed: TypeError: /Users/ivan/dev/react-grid-layout/node_modules/react-hot-loader/index.js!/Users/ivan/dev/react-grid-layout/test/dev-hook.jsx: Cannot call method 'match' of undefined
    at urlParse (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/node_modules/source-map/lib/source-map/util.js:37:22)
    at normalize (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/node_modules/source-map/lib/source-map/util.js:86:15)
    at Array.map (native)
    at SourceMapConsumer.BasicSourceMapConsumer (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-consumer.js:287:23)
    at new SourceMapConsumer (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/node_modules/source-map/lib/source-map/source-map-consumer.js:25:9)
    at File.mergeSourceMap (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:473:31)
    at File.<anonymous> (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:522:23)
    at File.generate (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:488:24)
    at /Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/transformation/file.js:399:20
    at module.exports (/Users/ivan/dev/react-grid-layout/node_modules/babel-core/lib/babel/helpers/parse.js:35:14)
 @ multi main
```

**Comment by STRML** [comment]
That's odd. That looks like an internal babel error. See what you can
find... I'll troubleshoot as well.
