### ISSUE TITLE
Manual propTypes validation warning

### ISSUE THREAD

**Issue by jackychow** [STRML/react-grid-layout#417]
Since updating my React to 15.3.2, I am seeing this warning:

>Warning: You are manually calling a React.PropTypes validation function for the `minW` prop on `GridItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Not exactly sure since which react version this warning would start to appear. Since I know you guys are working on a V2 so probably this should be noted as manual validation would not be supposed in the next "major version" and React seems to be coming out with a major release every 6 months or so.

**Comment by STRML** [comment]
I believe this is fixed in the latest RGL release, could you please update
and verify?

**Comment by jackychow** [comment]
hey @STRML, hmmm I haven't tried the latest release. But unless the release includes changes that is not in the master branch, I believe this problem still exists in master?

https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L39

**Comment by STRML** [comment]
No, custom `propTypes` validators is not the issue, the issue is calling something like `this.constructor.propTypes.minX(val)`.

**Comment by jackychow** [comment]
ahhh @STRML , you are right. Sorry I misunderstood the issue!
updated to the latest release and you are correct, the warning is no longer there. 
Thanks!
