### ISSUE TITLE
Re: Dragging and autoscroll bug

### ISSUE THREAD

**Issue by quangdng** [STRML/react-grid-layout#532]
Hi there,

Thanks for making this great component. I am facing a little annoying bug as mentioned in the title. When I drag a tile to the top or the bottom of the container, the browser didn't scroll and makes it very hard to reorder the tile.

Been searching for a solution but no luck. Could you please kindly help me in this matter? Thanks a lot.

**Comment by tsnevillecom** [comment]
I'm having the same issue. The container will not scroll.

**Comment by dherbolt** [comment]
Hi,
I'm having the same issue. Scroll when dragging tile works fine in Safari but not in Chorme. I have just tested in on your example:
https://strml.github.io/react-grid-layout/examples/4-grid-property.html

Used SW:
Safari Version 10.1.1 (12603.2.4)
Google Chrome Version 59.0.3071.86 (Official Build) (64-bit)

**Comment by larrydahooster** [comment]
I am encountering the same problem with chrome. It definitely was working but must have been broken at some point. 

I also figured out that a different grid engine (gridster) that is running in a different project stopped scrolling in Chrome as well.

**Comment by dherbolt** [comment]
This package depends on react-draggable. It looks like there is couse of this issue:
https://github.com/mzabriskie/react-draggable/issues/240

**Comment by chetanmotamarri** [comment]
Any update on this ? Facing same issue.

**Comment by dherbolt** [comment]
It should be fixed by https://github.com/mzabriskie/react-draggable/pull/261

**Comment by tyrsensei** [comment]
Hi,

Still not functional under chrome, as I can see in [this exemple](https://strml.github.io/react-grid-layout/examples/12-prevent-collision.html)

(works under IE and Firefox)

**Comment by dherbolt** [comment]
Hi @tyrsensei ,
it work in example for me in Chrome (MacOS) and Safari.

**Comment by tyrsensei** [comment]
Retested, and still KO for me.

Specs : `Ubuntu 16.04`, `Chrome Version 64.0.3282.186 (Build officiel) (64 bits)`

Behaviour : When dragging, most of the time, it gets down a little bit, but no further. Sometimes, it just works. Haven't managed to find what may or may not be a pattern :cry: I can use the mouse wheel to get down, but it's not an option on tablets/phones.

**Comment by tyrsensei** [comment]
When playing with it, just found out what was the reason of the different behaviours was !

It seems that if I drag too far/fast down the screen, that's when it stops scrolling. Indeed, if I approach the bottom of the screen "gently", it works every time.

**Comment by dherbolt** [comment]
It seems to be working for me on Safari, Chrome (MacOS)

**Comment by harrisonturton** [comment]
Not working on Firefox (MacOS)

**Comment by chiara-crovetto** [comment]
Still not working on Chrome 83
