### ISSUE TITLE
[Bug] onWidthChange is only called on breakpoint changes

### ISSUE THREAD

**Issue by species-gh** [STRML/react-grid-layout#769]
Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

Hi,
I noticed that the callback `onWidthChange` is only called when there is a breakpoint change, but _not on every_ change of width, like the name suggests. Calling it on every width change makes this callback a lot more useful, since there already is a callback for breakpoint changes (`onBreakpointChange`).
This behavior can be observed in [this example](https://species-gh.github.io/react-grid-layout/examples/15-badOnWidthChange.html).

Greetings,
species

**Comment by STRML** [comment]
Fixed in #770

**Comment by sgordon3** [comment]
Can a new version be published to include this pull request?

**Comment by dioscuroi** [comment]
Has this been published to npm? onWidthChange is still not being called unless breakpoint-change occurs..;;;

**Comment by mankinchi** [comment]
No update on this?
