### ISSUE TITLE
Grid initial rendering issue

### ISSUE THREAD

**Issue by saravanannnallasamy** [STRML/react-grid-layout#879]
I have used react-grid-layout(@0.13.5) in my previous projects. It just worked fine.
In my current project, when screen is loaded the grids are arranged in stack of items instead of in a linear manner.

![image](https://user-images.githubusercontent.com/25293768/48399557-f858d400-e749-11e8-9d0f-46bd3e4db5f3.png)

When i use Inspect(ctrl+shift+i) or drag the inspect window the grid-items are re-arranged automatically. I don't know whats the reason.
Current version: 0.14.7, tried 0.16.6 and 0.13.5.
react- @15.6.1

![image](https://user-images.githubusercontent.com/25293768/48399583-11fa1b80-e74a-11e8-8f59-a9e09aa0db01.png)

i this grid layout re-arranged on screen size change. But in initial loading it is not working

**Comment by trautmaa** [comment]
I am having a similar issue. No widget stacking, but layout width is initially larger than the screen. When I resize the window, everything resizes. 

React- @16.0.0
React-Grid-Layout- @0.16.6

**Comment by trautmaa** [comment]
@saravanannnallasamy Consider https://github.com/maslianok/react-resize-detector as a temporary fix

**Comment by mnoster** [comment]
Having the same issue. Works only when resizing the window.

**Comment by anarchistgeek** [comment]
Same issue... Could anyone provide a workaround for this? @STRML

**Comment by mnoster** [comment]
@anarchistgeek  @saravanannnallasamy 

I created a very simple workaround by editing the package code. 
I call the `windowResize` function manually on first load.

1. Open `node_modules/react-grid-layout/WidthProvider.js`
2.  Scroll down to the `render` function around line 73
3. Replace with the following code:
```
    var firstLoad = true
    
    WidthProvider.prototype.render = function render() {
      var self = this;
      if (firstLoad) {
        setTimeout(function () {
          self.onWindowResize();
        }, 500)
        firstLoad = false;
      }

      var _props = this.props,
        measureBeforeMount = _props.measureBeforeMount,
        rest = _objectWithoutProperties(_props, ["measureBeforeMount"]);

      if (measureBeforeMount && !this.mounted) {
        return _react2.default.createElement("div", { className: this.props.className, style: this.props.style });
      }

      return _react2.default.createElement(ComposedComponent, _extends({}, rest, this.state));
    };
```

4. Restart React/node frontend server.
5. Complete

**Comment by mnoster** [comment]
The only code I added was:
```
    var firstLoad = true

```

AND

```

      var self = this;
      if (firstLoad) {
        setTimeout(function () {
          self.onWindowResize();
        }, 500)
        firstLoad = false;
      }
```

**Comment by mnoster** [comment]
@saravanannnallasamy @trautmaa 

I fixed the issue on my own fork of the repo. In the meantime, you may use it if you like.

Just run `npm install --save https://github.com/mnoster/react-grid-layout`

**Comment by saravanannnallasamy** [comment]
> Just run npm install --save https://github.com/mnoster/react-grid-layout

It worked for me, thank you very much  @mnoster

**Comment by richbai90** [comment]
Has anyone opened a PR for this yet?

**Comment by bgold0** [comment]
This fixed my issue and should really be added.

**Comment by cashwanikumar** [comment]
I have same issue.
I have fixed this by just triggering resize event.

`
	componentDidMount() {
		// Resize grid-layout after initial rendering
		setTimeout(() => {
			window.dispatchEvent(new Event('resize'))
		}, 500)
	}
`

**Comment by ChristopherHButler** [comment]
Seems this is still an issue in 2022 and adding a resize event does not seem to work for me. Anyone else have a fix for this?

**Comment by nosachamos** [comment]
Same for me - the workaround above is not working for me either.
